# Workflow: Variables and secrets example
# Summary: Shows environment variable usage for Docker build, login,
# and publish steps (including hard-coded credentials for demo only).
name: Exploring variables and secrets

on: push

jobs: 
  docker:
    if: false # This is to prevent the workflow from running accidentally.
    runs-on: ubuntu-latest
    steps:
      - name: Docker build
        env:
          CONTAINER_REGISTRY: docker.io
          DOCKER_USERNAME: giri
          IMAGE_NAME: github-actions-nginx
        run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest .

      - name: Docker login
        env:
          DOCKER_USERNAME: giri
          DOCKER_PASSWORD: s3cUrePaSsw0rd
        run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
        
      - name: Docker publish
        env:
          CONTAINER_REGISTRY: docker.io
          DOCKER_USERNAME: giri
          IMAGE_NAME: github-actions-nginx
        run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    if: false # This is to prevent the workflow from running accidentally.
    needs: docker
    runs-on: ubuntu-latest
    env:
      CONTAINER_REGISTRY: docker.io
      DOCKER_USERNAME: giri
      IMAGE_NAME: github-actions-nginx
    steps:
      - name: Deploy
        run: echo "Deploying the image to production environment ..."