
name: ch1-p9 Matrix configuration example

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    if: false # This is to prevent the workflow from running accidentally.
    strategy:
      fail-fast: false # Continue running all matrix combinations even if one fails
      max-parallel: 2 # Limit the number of concurrent jobs to prevent resource exhaustion
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [hello-world, alpine]
        exclude:
          - os: windows-latest
            images: alpine # Alpine image is not compatible with Windows OS
        include:
          - os: ubuntu-20.04
            images: amd64/alpine

    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo docker info
        run: docker info

      - name: Run image ${{ matrix.os }}
        run: docker run ${{ matrix.images }}
        
  # deploy-on-ubuntu:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Echo docker info
  #       run: docker info

  #     - name: Run image
  #       run: docker run hello-world
  # deploy-on-windows:
  #   runs-on: windows-latest

  #   steps:
  #     - name: Echo docker info
  #       run: docker info

  #     - name: Run image
  #       run: docker run hello-world


