
name: ch1-p8 Github events - concurrency

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Docker build
        run: echo "docker build -t ${{vars.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{vars.IMAGE_NAME}}:latest"

      - name: Docker login
        run: echo "docker login --username=${{vars.DOCKER_USERNAME}} --password=${{secrets.DOCKER_PASSWORD}}"

      - name: Docker publish
        run: echo "docker push -t ${{vars.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{vars.IMAGE_NAME}}:latest"

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    timeout-minutes: 1 # Set a job-leveltimeout to prevent long-running deployments

    concurrency: 
      group: prod-deploy
      cancel-in-progress: true
    
      
    steps:
      - name: Deploy
        timeout-minutes: 1 # Set a step-level timeout to prevent long-running deployments
        run: |
          echo "docker run -d -p 8080:80 ${{vars.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{vars.IMAGE_NAME}}:latest"
          sleep 120s # Simulate a long-running deployment process

