name: Use repository level variables and secrets

on: push

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Docker build
        run: echo "docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$env.IMAGE_NAME:latest"

      - name: Docker login
        run: echo "docker login --username=$DOCKER_USERNAME --password=${{secrets.DOCKER_PASSWORD}}"

      - name: Docker publish
        run: echo "docker push -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$env.IMAGE_NAME:latest"

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$env.IMAGE_NAME:latest"
