
name: Use workflow level env variables and secrets

on: push

env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: giri
  IMAGE_NAME: github-actions-nginx
  DOCKER_PASSWORD: s3cUrePaSsw0rd1

jobs:
  docker:
    if: false # This is to prevent the workflow from running accidentally.
    runs-on: ubuntu-latest

    steps:
      - name: Docker build
        run: echo "docker build -t ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest"

      - name: Docker login
        run: echo "docker login --username=${{env.DOCKER_USERNAME}} --password=${{env.DOCKER_PASSWORD}}"

      - name: Docker publish
        run: echo "docker push -t ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest"

  deploy:
    if: false # This is to prevent the workflow from running accidentally.
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "docker run -d -p 8080:80 ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest"
