# Workflow: Variables and secrets example
# Summary: Shows environment variable usage for Docker build, login,
# and publish steps (including hard-coded credentials for demo only).
name: Exploring variables and secrets

on: push

env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: giri
  IMAGE_NAME: github-actions-nginx
  DOCKER_PASSWORD: s3cUrePaSsw0rd1

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Docker build
        run: docker build -t ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest

      - name: Docker login
        run: docker login --username=${{env.DOCKER_USERNAME}} --password=${{env.DOCKER_PASSWORD}}

      - name: Docker publish
        run: docker push -t ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying the image to production environment ..."
