
name: ch1-p6 Use variables and secrets from repository settings

on: push

jobs:
  docker:
    if: false # This is to prevent the workflow from running accidentally.
    runs-on: ubuntu-latest

    steps:
      - name: Docker build
        run: echo "docker build -t ${{vars.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{vars.IMAGE_NAME}}:latest"

      - name: Docker login
        run: echo "docker login --username=${{vars.DOCKER_USERNAME}} --password=${{secrets.DOCKER_PASSWORD}}"

      - name: Docker publish
        run: echo "docker push -t ${{vars.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{vars.IMAGE_NAME}}:latest"

  deploy:
    if: false # This is to prevent the workflow from running accidentally.
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "docker run -d -p 8080:80 ${{vars.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{vars.IMAGE_NAME}}:latest"
