name: My workflow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v6
            - name: welcome
              run: echo "My first github"
            - name: list files
              run: ls
            - name: read file
              run: cat README.md